micronaut:
  application:
    name: mptasinski-co-brick-task

#there was a typo in the task *.yml example that gave me a nightmare here
colors:
  mapping:
    red: "255,0,0"
    green: "0,255,0"
    blue: "0,0,255"