micronaut:
  application:
    name: mptasinski-co-brick-task

#there was a typo in the task *.yml example that gave me a nightmare here
colors:
  color: yes
  mapping:
    red: "255,0,0"
    green: "0,255,0"
    blue: "0,0,255"

mongodb:
  uri: mongodb://username:password@localhost:27017/databaseName
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20